// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// apwnd_window_internal
List apwnd_window_internal(IntegerMatrix x, int a, int b);
RcppExport SEXP _genoscapeRtools_apwnd_window_internal(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(apwnd_window_internal(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// sample_from_angsd_probs
IntegerMatrix sample_from_angsd_probs(NumericVector x, CharacterVector samples, CharacterVector snps, double thresh);
RcppExport SEXP _genoscapeRtools_sample_from_angsd_probs(SEXP xSEXP, SEXP samplesSEXP, SEXP snpsSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type snps(snpsSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_from_angsd_probs(x, samples, snps, thresh));
    return rcpp_result_gen;
END_RCPP
}
// mat_cumul_cpp
NumericMatrix mat_cumul_cpp(NumericMatrix x, int dim);
RcppExport SEXP _genoscapeRtools_mat_cumul_cpp(SEXP xSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_cumul_cpp(x, dim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genoscapeRtools_apwnd_window_internal", (DL_FUNC) &_genoscapeRtools_apwnd_window_internal, 3},
    {"_genoscapeRtools_sample_from_angsd_probs", (DL_FUNC) &_genoscapeRtools_sample_from_angsd_probs, 4},
    {"_genoscapeRtools_mat_cumul_cpp", (DL_FUNC) &_genoscapeRtools_mat_cumul_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_genoscapeRtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
