# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' hello world
#' @export
rcpp_hello <- function() {
    .Call('genoscapeRtools_rcpp_hello', PACKAGE = 'genoscapeRtools')
}

#' return a matrix of cumumlative sums along the rows or colums
#' @param x a numeric matrix
#' @param dim 1 for rows, 2 for columns
#' @export
mat_cumul_cpp <- function(x, dim) {
    .Call('genoscapeRtools_mat_cumul_cpp', PACKAGE = 'genoscapeRtools', x, dim)
}

